# Generated by Django 5.1.4 on 2024-12-28 22:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_relevance_delete_statistics2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('table', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='graphics_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
