# Generated by Django 5.1.4 on 2025-01-01 17:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_top20_delete_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
