# Generated by Django 5.1.4 on 2025-01-01 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_info_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top202',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('table', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
