# Generated by Django 5.1.4 on 2025-01-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_top202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top202',
            new_name='Top20Analytic',
        ),
    ]
