# Generated by Django 5.1.4 on 2025-01-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_rename_top202_top20analytic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top20analytic',
            name='image',
            field=models.ImageField(upload_to='graphics_images'),
        ),
    ]
